import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AOSInit } from "../component/AOSinit";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main className="flex-1 md:ml-64 p-6">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AOSInit />
          {children}
        </body>
      </main>
    </html>
  );
}


